# Generated by Django 3.1.7 on 2021-04-26 15:37

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=128)),
                ('permission_code', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'Username already exists'}, max_length=128, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('password', models.CharField(max_length=320)),
                ('email', models.CharField(max_length=128, validators=[django.core.validators.EmailValidator()], verbose_name='Email of Account')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('join_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time join')),
                ('permissions', models.ManyToManyField(to='Account.Permission')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
