# Generated by Django 3.1.7 on 2021-04-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission_code',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_name',
            field=models.CharField(max_length=250),
        ),
    ]
