# Generated by Django 3.1.7 on 2021-05-03 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20210502_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='join_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 6, 36, 15, 41666, tzinfo=utc), verbose_name='Time join'),
        ),
    ]
