# Generated by Django 3.1.7 on 2021-05-03 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20210503_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='join_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 6, 39, 7, 160611, tzinfo=utc), verbose_name='Time join'),
        ),
    ]
