# Generated by Django 3.1.7 on 2021-05-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20210503_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='join_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 42, 26, 964599), verbose_name='Time join'),
        ),
    ]
