# Generated by Django 3.1.7 on 2021-05-03 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_auto_20210503_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='join_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 11, 15, 37, 365510, tzinfo=utc), verbose_name='Time join'),
        ),
    ]
