# Generated by Django 3.1.7 on 2021-05-05 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_auto_20210503_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='join_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time join'),
        ),
    ]
