# Generated by Django 3.1.7 on 2021-04-26 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=250)),
                ('group_course', models.CharField(choices=[('Sc', 'Science'), ('So', 'Society'), ('Ph', 'Physical')], max_length=2)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='StudyDocument',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('size', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=100)),
                ('file_data', models.FileField(upload_to='StudyDocument/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'study_document',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('shift', models.CharField(choices=[('M1', '7:15-8:00'), ('M2', '8:10-8:55'), ('M3', '9:05-9:50'), ('M4', '10:05-10:50'), ('M5', '11:00-11:45'), ('A1', '13:00-13:45'), ('A2', '13:55-14:10'), ('A3', '14:50-15:35'), ('A4', '15:50-16:35'), ('A5', '16:45-17:30')], max_length=2)),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thusday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher')),
            ],
            options={
                'db_table': 'time_table',
            },
        ),
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('note', models.TextField()),
                ('student_num', models.IntegerField()),
                ('classification', models.CharField(choices=[('A', 'Tot'), ('B', 'Kha'), ('C', 'Trung Binh'), ('D', 'Yeu')], max_length=1)),
                ('shift', models.CharField(choices=[('M1', '7:15-8:00'), ('M2', '8:10-8:55'), ('M3', '9:05-9:50'), ('M4', '10:05-10:50'), ('M5', '11:00-11:45'), ('A1', '13:00-13:45'), ('A2', '13:55-14:10'), ('A3', '14:50-15:35'), ('A4', '15:50-16:35'), ('A5', '16:45-17:30')], max_length=2)),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thusday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('study_week', models.CharField(max_length=128)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher')),
            ],
            options={
                'db_table': 'class_record',
            },
        ),
    ]
