# Generated by Django 3.1.7 on 2021-05-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
        ('School', '0002_auto_20210507_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_year', models.CharField(max_length=250)),
                ('semester', models.SmallIntegerField(max_length=2)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher')),
            ],
            options={
                'db_table': 'teaching_information',
            },
        ),
    ]
