# Generated by Django 3.1.7 on 2021-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_teachinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachinginfo',
            name='semester',
            field=models.SmallIntegerField(),
        ),
    ]
