# Generated by Django 3.1.7 on 2021-05-22 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_auto_20210515_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='school_year',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='semester',
            field=models.SmallIntegerField(default=1),
        ),
    ]
