# Generated by Django 3.1.7 on 2021-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0006_auto_20210522_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='school_year',
            field=models.CharField(default='2021-2022', max_length=250),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timetable',
            name='study_week',
            field=models.CharField(default='Week 1', max_length=128),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thusday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=3),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='shift',
            field=models.CharField(choices=[('M1', '7:15-8:00'), ('M2', '8:10-8:55'), ('M3', '9:05-9:50'), ('M4', '10:05-10:50'), ('M5', '11:00-11:45'), ('A1', '13:00-13:45'), ('A2', '13:55-14:10'), ('A3', '14:50-15:35'), ('A4', '15:50-16:35'), ('A5', '16:45-17:30')], default='M1', max_length=2),
        ),
    ]
