# Generated by Django 3.1.7 on 2021-05-22 18:52

import School.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0008_auto_20210522_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studydocument',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='studydocument',
            name='semester',
        ),
        migrations.AddField(
            model_name='studydocument',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='School.classroom'),
        ),
        migrations.AlterField(
            model_name='studydocument',
            name='file_data',
            field=models.FileField(upload_to=School.models.upload_to),
        ),
    ]
