# Generated by Django 3.1.7 on 2021-05-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0009_auto_20210522_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studydocument',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='studydocument',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studydocument',
            name='size',
        ),
    ]
