# Generated by Django 3.1.7 on 2021-05-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0010_auto_20210522_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studydocument',
            old_name='file_data',
            new_name='file',
        ),
    ]
