# Generated by Django 3.1.7 on 2021-05-22 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0011_auto_20210522_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydocument',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 22, 13, 51, 342941)),
        ),
    ]
