# Generated by Django 3.1.7 on 2021-05-22 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0012_studydocument_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydocument',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 22, 28, 15, 509349)),
        ),
    ]
