# Generated by Django 3.1.7 on 2021-05-24 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0013_auto_20210522_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydocument',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 20, 27, 38, 154055)),
        ),
    ]
