# Generated by Django 3.1.7 on 2021-05-24 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0014_auto_20210524_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydocument',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
