# Generated by Django 3.1.7 on 2021-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0015_auto_20210524_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.IntegerField(choices=[(2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thusday'), (6, 'Friday'), (7, 'Saturday'), (8, 'Sunday')], default='2'),
        ),
    ]
