# Generated by Django 3.1.7 on 2021-05-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedDevice',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
