# Generated by Django 3.1.7 on 2021-05-24 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_auto_20210514_2027'),
        ('Device', '0003_borroweddevice_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroweddevice',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher'),
        ),
    ]
