# Generated by Django 3.1.7 on 2021-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_auto_20210503_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='health',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
