# Generated by Django 3.1.7 on 2021-05-07 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0004_auto_20210507_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
    ]
