# Generated by Django 3.1.7 on 2021-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0005_auto_20210507_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
