# Generated by Django 3.1.7 on 2021-05-07 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0006_auto_20210507_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
