# Generated by Django 3.1.7 on 2021-05-07 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0007_auto_20210507_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
