# Generated by Django 3.1.7 on 2021-05-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0008_auto_20210507_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='disease',
        ),
    ]
