# Generated by Django 3.1.7 on 2021-05-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0009_remove_health_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='disease',
            field=models.TextField(null=True),
        ),
    ]
