# Generated by Django 3.1.7 on 2021-04-26 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Person', '0001_initial'),
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, unique=True)),
                ('admission_year', models.DateField()),
                ('status', models.CharField(choices=[('L', 'Learing'), ('O', 'Out'), ('D', 'Done'), ('F1', 'Fail 1 year'), ('F2', 'Fail 2 years')], max_length=2)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
                ('achievement', models.ManyToManyField(to='Person.Achievement')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.classroom')),
                ('health', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Person.health')),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('school_year', models.CharField(max_length=250)),
                ('test_p', models.FloatField()),
                ('mid_term_p', models.FloatField()),
                ('term_p', models.FloatField()),
                ('final_term_p', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid3, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('father_or_mother', models.CharField(choices=[('F', 'Father'), ('M', 'Mother')], max_length=1)),
                ('job', models.CharField(max_length=250)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Person.person')),
                ('student', models.ManyToManyField(to='Student.Student')),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('score', models.CharField(choices=[('T', 'Tot'), ('K', 'Kha'), ('TB', 'Trung binh'), ('Y', 'Yeu')], max_length=2)),
                ('term', models.SmallIntegerField()),
                ('school_year', models.CharField(max_length=250)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'db_table': 'conduct',
            },
        ),
    ]
