# Generated by Django 3.1.7 on 2021-05-05 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0003_auto_20210503_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(related_name='parent', to='Student.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.account'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='School.classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('L', 'Learing'), ('O', 'Out'), ('D', 'Done'), ('F1', 'Fail 1 year'), ('F2', 'Fail 2 years')], max_length=2, null=True),
        ),
    ]
