# Generated by Django 3.1.7 on 2021-05-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
        ('Student', '0004_auto_20210505_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('L', 'Learing'), ('O', 'Out'), ('D', 'Done'), ('F1', 'Fail 1 year'), ('F2', 'Fail 2 years')], max_length=2),
        ),
    ]
