# Generated by Django 3.1.7 on 2021-05-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20210505_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.DateField(default='14-7-2015'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('L', 'Learing'), ('O', 'Out'), ('D', 'Done'), ('F1', 'Fail 1 year'), ('F2', 'Fail 2 years')], default='L', max_length=2),
        ),
    ]
