# Generated by Django 3.1.7 on 2021-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_auto_20210505_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
