# Generated by Django 3.1.7 on 2021-05-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0008_auto_20210507_2340'),
        ('Student', '0009_auto_20210507_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='achievement',
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.parent')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'db_table': 'student_parent',
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.achievement')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'db_table': 'student_achievement',
            },
        ),
    ]
