# Generated by Django 3.1.7 on 2021-05-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_auto_20210508_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentachievement',
            old_name='achievement_id',
            new_name='achievement',
        ),
        migrations.RenameField(
            model_name='studentachievement',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentparent',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='studentparent',
            old_name='student_id',
            new_name='student',
        ),
    ]
