# Generated by Django 3.1.7 on 2021-05-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_auto_20210515_0902'),
        ('Student', '0011_auto_20210508_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Grade',
        ),
    ]
