# Generated by Django 3.1.7 on 2021-05-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_auto_20210515_0902'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grade',
            table='grade',
        ),
    ]
