# Generated by Django 3.1.7 on 2021-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_auto_20210515_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_term_p',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='mid_term_p',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='term_p',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='test_p',
            field=models.FloatField(null=True),
        ),
    ]
