# Generated by Django 3.1.7 on 2021-05-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_auto_20210514_2027'),
        ('Student', '0014_auto_20210515_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher'),
        ),
    ]
