# Generated by Django 3.1.7 on 2021-05-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_grade_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.DateField(default='2015-7-14'),
        ),
    ]
